### PR TITLE
[MMCA-4734] Updated PVAT statements page to be consistent with other statement pages

### PR DESCRIPTION
**Pull request by wg-hmrc**

### CODE REVIEW

**Comment by tyagikumarvineet** [comment]
as per ticket , we should also remove below statements. Let me know if i am missing something.

Statements are only created for periods in which you imported goods.

You can view and download your statements for the last 6 months on this service. Older statements can be requested using the request options at the bottom of this page.

**Review by AdamCoops — APPROVED** [review]

**Comment by tyagikumarvineet** [comment]
As per ticket, it should be as below. Have a look

**As per ticket**

Your statements will usually be available after the 10th working day of each month.


**With existing code**  

Your certificates will usually be available after the 10th working day of each month.

**Comment by tyagikumarvineet** [comment]
The Welsh translation for 'Declarations made using CHIEF' as per ticket should be as below

**As per ticket** 

Datganiadau a wnaed gan ddefnyddio CHIEF

**With existing code**

Datganiadau a wnaed gan ddefnyddio’r gwasanaeth CHIEF

**Comment by wg-hmrc** [comment]
> The Welsh translation for 'Declarations made using CHIEF' as per ticket should be as below. Let me know if the existing is correct Welsh translation
> 
> **As per ticket**
> 
> Datganiadau a wnaed gan ddefnyddio CHIEF
> 
> **With existing code**
> 
> Datganiadau a wnaed gan ddefnyddio’r gwasanaeth CHIEF

@tyagikumarvineet regarding your comment for welsh.. I’m re-using what’s been used in C79 and Duty Deferment.
The purpose of this ticket is to make all pages in-sync

**Comment by tyagikumarvineet** [comment]
> > The Welsh translation for 'Declarations made using CHIEF' as per ticket should be as below. Let me know if the existing is correct Welsh translation
> > **As per ticket**
> > Datganiadau a wnaed gan ddefnyddio CHIEF
> > **With existing code**
> > Datganiadau a wnaed gan ddefnyddio’r gwasanaeth CHIEF
> 
> @tyagikumarvineet regarding your comment for welsh.. I’m re-using what’s been used in C79 and Duty Deferment. The purpose of this ticket is to make all pages in-sync

@wg-hmrc okay, if you are saying that is the correct translation, I will approve it. Only thing here is that Welsh translation in the existing code does not match the translation provided in the ticket. Will mention this (for Sujay) in the ticket  so that he can check once he is back

**Review by tyagikumarvineet — APPROVED** [review]

**Pull request merged**
